name : Main Workflow

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Installation des dépendances
        run: npm install

      - name: Tests Unitaires
        run: npm run test-unit

      - name: Tests Fonctionnels
        run: npm run test-functional

      - name: Build de l'application
        run: npm run build


      - name: Déploiement Netlify (Production)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './front/build'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} # Personal access tokens
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} # project-details